export const DIVINATION_READING_PRICE_TWD = 200 as const
export const DIVINATION_READING_PRICE_LABEL = `NT$${DIVINATION_READING_PRICE_TWD}`
export const DIVINATION_READING_PAYMENT_MESSAGE =
  `本次 AI 占卜解讀需 ${DIVINATION_READING_PRICE_LABEL}。`
